server:
  port: 8094
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/ #\u6307\u5411\u670D\u52A1\u6CE8\u518C\u4E2D\u5FC3
spring:
  application:
    name: service-feign #\u7ED9\u5B9E\u4F8B\u53D6\u4E00\u4E2A\u540D\u5B57
feign:
  hystrix:
    enabled: true  # D\u7248\u672C\u540E\uFF0Cfeign\u9ED8\u8BA4\u4E0D\u5F00\u542F\u77ED\u8DEF\u5668\uFF0C\u9700\u8981\u624B\u52A8\u5F00\u542F
