server:
  port: 8094
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/ #\u6307\u5411\u670D\u52A1\u6CE8\u518C\u4E2D\u5FC3
spring:
  application:
    name: service-feign #\u7ED9\u5B9E\u4F8B\u53D6\u4E00\u4E2A\u540D\u5B57
